name = "tiktok-stats"
main = "src/index.js"
compatibility_date = "2024-01-01"

[[kv_namespaces]]
binding = "CACHE"
id = "c80507619c4c4305a5d56cc56b36cd34"

[triggers]
crons = ["0 1 * * *"] # Chạy vào 1h00 sáng UTC mỗi ngày

# [vars] env variables công khai
# TIKTOK_USERNAME = "nguyendevs"
